name: cd

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: "github.event.pull_request.merged == true && !contains(github.event.pull_request.head.message, 'skipci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # No point testing this immediately before doing it. TODO refactor to CI.
      - name: Publish latest package to PyPI
        run: |
          pip install uv twine
          uv pip install --system
          python -m build
          twine upload dist/* --skip-existing --username __token__ --password ${{ secrets.PYPI_TOKEN }}

  release:
    # This job will only run if the PR has been merged (and not closed without merging).
    if: "github.event.pull_request.merged == true && !contains(github.event.pull_request.head.message, 'skipci')"
    runs-on: ubuntu-latest
    needs: [publish]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get package version
        id: version
        run: echo "::set-output name=package_version::$(python setup.py --version)"

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, no need to create your own.
        with:
          tag_name: ${{ steps.version.outputs.package_version }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false
